//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.API.Properties.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IngredientTypeDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientTypeDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.API.Properties.Ingredients.IngredientTypeDescriptions", typeof(IngredientTypeDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereals and Pulses are types of grains. Cereals are majorly produced in many countries. It is highly rich in carbohydrates, while pulses are rich in proteins. Pulses are grown in less quantity than cereals. The cereals are the grasses, whereas pulses are leguminous. The cereals belong to the Poaceae family (monocot), while pulses are crops that produce pods. Let us learn the difference between cereals and pulses.
        ///
        ///Cereals and Pulses are small, dry, and hard seeds. There are five types of grains; cereal gr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CerealsAndPulses {
            get {
                return ResourceManager.GetString("CerealsAndPulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dairy products or milk products, also known as lacticinia, are food products made from (or containing) milk. The most common dairy animals are cow, water buffalo, nanny goat, and ewe. Dairy products include common grocery store food items in the Western world such as yogurt, cheese, milk and butter. A facility that produces dairy products is known as a dairy. Dairy products are consumed worldwide to varying degrees (see consumption patterns worldwide). Some people avoid some or all dairy products either bec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DairyProducts {
            get {
                return ResourceManager.GetString("DairyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In botany, a fruit is the seed-bearing structure in flowering plants that is formed from the ovary after flowering (see Fruit anatomy).
        ///
        ///Fruits are the means by which flowering plants (also known as angiosperms) disseminate their seeds. Edible fruits in particular have long propagated using the movements of humans and other animals in a symbiotic relationship that is the means for seed dispersal for the one group and nutrition for the other; in fact, humans and many other animals have become dependent on  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fruits {
            get {
                return ResourceManager.GetString("Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat is animal flesh that is eaten as food. Humans have hunted, farmed, and scavenged other animals for meat since prehistoric times. The establishment of settlements in the Neolithic Revolution allowed the domestication of animals such as chickens, sheep, rabbits, pigs, and cattle. This eventually led to their use in meat production on an industrial scale in slaughterhouses..
        /// </summary>
        public static string Meat {
            get {
                return ResourceManager.GetString("Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With &quot;nuts&quot; we mean all shelled fruits (such as walnuts, hazelnuts, almonds, etc.). Examples of oil seeds are pumpkin seeds, sesame, sunflower, flax, which have nutritional characteristics to similar nuts, so the two types of food are brought together in the same group..
        /// </summary>
        public static string NutsAndOilseeds {
            get {
                return ResourceManager.GetString("NutsAndOilseeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other ingredients..
        /// </summary>
        public static string OtherIngredients {
            get {
                return ResourceManager.GetString("OtherIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seafood is any form of sea life regarded as food by humans, prominently including fish and shellfish. Shellfish include various species of molluscs (e.g., bivalve molluscs such as clams, oysters, and mussels, and cephalopods such as octopus and squid), crustaceans (e.g. shrimp, crabs, and lobster), and echinoderms (e.g. sea cucumbers and sea urchins). Historically, marine mammals such as cetaceans (whales and dolphins) as well as seals have been eaten as food, though that happens to a lesser extent in moder [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Seafood {
            get {
                return ResourceManager.GetString("Seafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spices and herbs are defined as plant derived substances that add flavor to any dish. It is difficult to distinguish between the two. Spices can come from the following plant parts: roots, rhizomes, stems, leaves, bark, flowers, fruits, and seeds. Herbs are typically thought of as non-woody plants..
        /// </summary>
        public static string SpicesAndHerbs {
            get {
                return ResourceManager.GetString("SpicesAndHerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar is the generalized name for sweet, short-chain, soluble carbohydrates, many of which are used in food. They are composed of carbon, hydrogen, and oxygen. There are various types of sugar derived from different sources..
        /// </summary>
        public static string SugarAndSugarProducts {
            get {
                return ResourceManager.GetString("SugarAndSugarProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetables are parts of plants that are consumed by humans or other animals as food. The original meaning is still commonly used and is applied to plants collectively to refer to all edible plant matter, including the flowers, fruits, stems, leaves, roots, and seeds. An alternative definition of the term is applied somewhat arbitrarily, often by culinary and cultural tradition. It may exclude foods derived from some plants that are fruits, flowers, nuts, and cereal grains, but include savoury fruits such as [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
    }
}
