//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.API.Properties.Ingredients {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IngredientImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientImages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.API.Properties.Ingredients.IngredientImages", typeof(IngredientImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_All_Purpose_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_All_Purpose_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Amaranth {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Amaranth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Arborio_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Arborio_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barley {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barnyard_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barnyard_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Basmati_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Basmati_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bean_Sprouts {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bean_Sprouts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bengal_Gram__Split_ {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bengal_Gram__Split_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_eyed_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_eyed_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Grams {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Grams", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Breadcrumbs {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breadcrumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Breads {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breads", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Brown_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Brown_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Buckwheat {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Buckwheat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Chickpeas {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Chickpeas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Cornmeal {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Cornmeal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Couscous {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Couscous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Finger_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Finger_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Gram_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Gram_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Green_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Green_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Black_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Black_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Green_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Green_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Jowar {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Jowar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Kidney_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Kidney_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Muesli {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Muesli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Oats {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Oats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pearl_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pearl_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pigeon_Pea {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pigeon_Pea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pressed_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pressed_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Puffed_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Puffed_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Semolina {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Semolina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Tapioca {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Tapioca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Water_Chestnut_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Water_Chestnut_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Bengal_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Bengal_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Brown_Lentils {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Brown_Lentils", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Wheat_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Wheat_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Blue_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Blue_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Brie_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Brie_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Butter {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Butter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Buttermilk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Buttermilk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cheddar_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cheddar_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Clarified_Butter {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Clarified_Butter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Condensed_Milk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Condensed_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cottage_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cottage_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Feta_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Feta_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gouda_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gouda_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gruyere_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gruyere_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Hung_Curd {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Hung_Curd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Khoya {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Khoya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mascarpone_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mascarpone_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Milk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mozzarella_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mozzarella_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Parmesan_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Parmesan_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Provolone_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Provolone_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Ricotta_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Ricotta_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Yogurt {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Yogurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Apples {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Apricots {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apricots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Banana {
            get {
                object obj = ResourceManager.GetObject("Fruits_Banana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Blueberries {
            get {
                object obj = ResourceManager.GetObject("Fruits_Blueberries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cape_Gooseberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cape_Gooseberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cherry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cherry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Coconut {
            get {
                object obj = ResourceManager.GetObject("Fruits_Coconut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cooking_Apples {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cooking_Apples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cranberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cranberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Currant {
            get {
                object obj = ResourceManager.GetObject("Fruits_Currant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Custard_Apple {
            get {
                object obj = ResourceManager.GetObject("Fruits_Custard_Apple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Dates {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Dried_Fruit {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dried_Fruit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Figs {
            get {
                object obj = ResourceManager.GetObject("Fruits_Figs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Grapefruit {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapefruit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Grapes {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Guava {
            get {
                object obj = ResourceManager.GetObject("Fruits_Guava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Indian_Gooseberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Indian_Gooseberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Jamun {
            get {
                object obj = ResourceManager.GetObject("Fruits_Jamun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Kiwi {
            get {
                object obj = ResourceManager.GetObject("Fruits_Kiwi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon_Juice {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Juice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon_Rind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Rind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lychee {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lychee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Mango {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mango", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Mulberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mulberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Olives {
            get {
                object obj = ResourceManager.GetObject("Fruits_Olives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Orange {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Orange_Rind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange_Rind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Papaya {
            get {
                object obj = ResourceManager.GetObject("Fruits_Papaya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Peach {
            get {
                object obj = ResourceManager.GetObject("Fruits_Peach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pear {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pineapple {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pineapple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Plum {
            get {
                object obj = ResourceManager.GetObject("Fruits_Plum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pomegranate {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pomegranate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Raisins {
            get {
                object obj = ResourceManager.GetObject("Fruits_Raisins", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Strawberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Strawberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Sultana {
            get {
                object obj = ResourceManager.GetObject("Fruits_Sultana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Tamarind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tamarind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Tomato {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tomato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Water_Chestnut {
            get {
                object obj = ResourceManager.GetObject("Fruits_Water_Chestnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Watermelon {
            get {
                object obj = ResourceManager.GetObject("Fruits_Watermelon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Bacon {
            get {
                object obj = ResourceManager.GetObject("Meat_Bacon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Beef {
            get {
                object obj = ResourceManager.GetObject("Meat_Beef", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken_Liver {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken_Liver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken_Stock {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken_Stock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chops {
            get {
                object obj = ResourceManager.GetObject("Meat_Chops", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Crab {
            get {
                object obj = ResourceManager.GetObject("Meat_Crab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Free_Range_Chicken {
            get {
                object obj = ResourceManager.GetObject("Meat_Free_Range_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Grass_Fed_Chicken {
            get {
                object obj = ResourceManager.GetObject("Meat_Grass_Fed_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Ham {
            get {
                object obj = ResourceManager.GetObject("Meat_Ham", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Keema {
            get {
                object obj = ResourceManager.GetObject("Meat_Keema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Kidney_Meat {
            get {
                object obj = ResourceManager.GetObject("Meat_Kidney_Meat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Lamb_Meat {
            get {
                object obj = ResourceManager.GetObject("Meat_Lamb_Meat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Mutton {
            get {
                object obj = ResourceManager.GetObject("Meat_Mutton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Mutton_Liver {
            get {
                object obj = ResourceManager.GetObject("Meat_Mutton_Liver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Organic_Chicken {
            get {
                object obj = ResourceManager.GetObject("Meat_Organic_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Partridge {
            get {
                object obj = ResourceManager.GetObject("Meat_Partridge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Pork {
            get {
                object obj = ResourceManager.GetObject("Meat_Pork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Quail {
            get {
                object obj = ResourceManager.GetObject("Meat_Quail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Skinned_Chicken {
            get {
                object obj = ResourceManager.GetObject("Meat_Skinned_Chicken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Stock {
            get {
                object obj = ResourceManager.GetObject("Meat_Stock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Turkey {
            get {
                object obj = ResourceManager.GetObject("Meat_Turkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Almonds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Almonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Blanched_Almonds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Blanched_Almonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Canola_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Canola_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Cashew_Nuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Cashew_Nuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Chia_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chia_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Chironji {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chironji", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Hazelnut {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Hazelnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Mustard_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Mustard_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Olive_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Olive_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Peanuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Peanuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Pine_Nuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pine_Nuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Pistachio {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pistachio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Poppy_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Poppy_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sesame_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sesame_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sunflower_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sunflower_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Walnuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Walnuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Agar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Agar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Ajinomoto {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Ajinomoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Almond_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Almond_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Alum {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Alum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Arrowroot {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Arrowroot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Baking_Powder {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Baking_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Baking_Soda {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Baking_Soda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Balsamic_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Balsamic_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Barfi {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Barfi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Beer {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Beer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Brown_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Brown_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Chocolate {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Chocolate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Chocolate_Chips {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Chocolate_Chips", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Cocoa {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cocoa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Coconut_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Coconut_Oil {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Coconut_Water {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Coffee {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coffee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Cognac {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cognac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Cornflour {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cornflour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Cranberry_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cranberry_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Desiccated_Coconut {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Desiccated_Coconut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Egg {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Egg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Fish_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Fish_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Flat_Noodles {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Flat_Noodles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Gelatin {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Gelatin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Glycerine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Glycerine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Gold_Leaves {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Gold_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Guchchi {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Guchchi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Hoisin_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Hoisin_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Jelly {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Jelly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Jus {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Jus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Lotus_Seeds {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Lotus_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Malt_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Malt_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Margarine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Margarine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Marzipan {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Marzipan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Mayonnaise {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Mayonnaise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Melon_Seeds {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Melon_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Meringue {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Meringue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Oyster_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Oyster_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Paan {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Paan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Papad {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Papad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Pasta {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Pasta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Petha {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Petha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Polenta {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Polenta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Quinoa {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Quinoa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Red_Wine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Red_Wine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Red_Wine_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Red_Wine_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Rice_Flour {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Rice_Noodles {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Noodles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Rice_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Rose_Water {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rose_Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Roux {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Roux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Rum {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Sake {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Screw_Pine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Screw_Pine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Sea_Salt {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sea_Salt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Sev {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sev", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Sharbat {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sharbat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Soy_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Soy_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Soya_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Soya_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Tartaric_Acid {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tartaric_Acid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Tea {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Tofu {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tofu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Tomato_Puree {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tomato_Puree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Tortilla {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tortilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vanilla_Essence {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vanilla_Essence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vegetable_Oil {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vegetable_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vermicelli {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vermicelli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vetiver {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vetiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vinaigrette {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vinaigrette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_White_Pepper {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_White_Pepper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_White_Wine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_White_Wine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OtherIngredients_Yeast {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Yeast", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
