//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.API.Properties.Ingredients {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IngredientImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientImages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.API.Properties.Ingredients.IngredientImages", typeof(IngredientImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_All_Purpose_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_All_Purpose_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Amaranth_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Amaranth_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Arborio_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Arborio_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barley_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barley_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barnyard_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barnyard_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Basmati_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Basmati_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bean_Sprouts_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bean_Sprouts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bengal_Gram__Split__Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bengal_Gram__Split__Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_eyed_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_eyed_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Gram_Images {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Gram_Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bread_Images {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bread_Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Breadcrumbs_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breadcrumbs_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Brown_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Brown_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Buckwheat_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Buckwheat_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Chickpeas_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Chickpeas_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Cornmeal_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Cornmeal_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Couscous_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Couscous_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Finger_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Finger_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Gram_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Gram_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Green_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Green_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Black_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Black_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Green_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Green_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Jowar_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Jowar_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Kidney_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Kidney_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Muesli_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Muesli_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Oats_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Oats_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pearl_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pearl_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pigeon_Pea_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pigeon_Pea_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pressed_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pressed_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Puffed_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Puffed_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Semolina_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Semolina_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Tapioca_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Tapioca_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Water_Chestnut_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Water_Chestnut_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Bengal_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Bengal_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Brown_Lentils_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Brown_Lentils_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Wheat_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Wheat_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Blue_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Blue_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Brie_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Brie_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Butter_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Butter_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Buttermilk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Buttermilk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cheddar_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cheddar_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Clarified_Butter_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Clarified_Butter_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Condensed_Milk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Condensed_Milk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cottage_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cottage_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Feta_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Feta_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gouda_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gouda_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gruyere_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gruyere_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Hung_Curd_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Hung_Curd_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Khoya_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Khoya_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mascarpone_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mascarpone_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Milk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Milk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mozzarella_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mozzarella_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Parmesan_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Parmesan_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Provolone_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Provolone_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Ricotta_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Ricotta_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Yogurt_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Yogurt_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Apples_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apples_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Apricots_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apricots_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Banana_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Banana_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Blueberries_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Blueberries_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cape_Gooseberry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cape_Gooseberry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cherry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cherry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Coconut_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Coconut_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cooking_Apples_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cooking_Apples_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Cranberry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cranberry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Currant_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Currant_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Custard_Apple_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Custard_Apple_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Dates_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dates_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Dried_Fruit_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dried_Fruit_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Figs_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Figs_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Grapefruit_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapefruit_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Grapes_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapes_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Guava_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Guava_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Indian_Gooseberry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Indian_Gooseberry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Jamun_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Jamun_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Kiwi_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Kiwi_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon_Juice_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Juice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lemon_Rind_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Rind_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Lychee_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lychee_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Mango_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mango_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Mulberry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mulberry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Olives_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Olives_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Orange_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Orange_Rind_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange_Rind_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Papaya_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Papaya_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Peach_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Peach_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pear_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pear_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pineapple_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pineapple_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Plum_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Plum_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Pomegranate_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pomegranate_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Raisins_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Raisins_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Strawberry_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Strawberry_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Sultana_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Sultana_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Tamarind_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tamarind_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Tomato_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tomato_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Water_Chestnut_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Water_Chestnut_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fruits_Watermelon_Image {
            get {
                object obj = ResourceManager.GetObject("Fruits_Watermelon_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Bacon_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Bacon_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Beef_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Beef_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken_Liver_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken_Liver_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chicken_Stock_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Chicken_Stock_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Chops_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Chops_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Crab_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Crab_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Free_Range_Chicken_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Free_Range_Chicken_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Grass_Fed_Chicken_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Grass_Fed_Chicken_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Ham_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Ham_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Keema_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Keema_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Kidney_Meat_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Kidney_Meat_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Lamb_Meat_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Lamb_Meat_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Meat_Stock_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Meat_Stock_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Mutton_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Mutton_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Mutton_Liver_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Mutton_Liver_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Organic_Chicken_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Organic_Chicken_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Partridge_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Partridge_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Pork_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Pork_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Quail_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Quail_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Skinned_Chicken_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Skinned_Chicken_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Meat_Turkey_Image {
            get {
                object obj = ResourceManager.GetObject("Meat_Turkey_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Almonds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Almonds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Blanched_Almonds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Blanched_Almonds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Canola_Oil_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Canola_Oil_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Cashew_Nuts_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Cashew_Nuts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Chia_Seeds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chia_Seeds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Chironji_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chironji_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Hazelnut_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Hazelnut_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Mustard_Oil_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Oil_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Mustard_Seeds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Seeds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Olive_Oil_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Olive_Oil_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Peanuts_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Peanuts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Pine_Nuts_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pine_Nuts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Pistachio_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pistachio_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Poppy_Seeds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Poppy_Seeds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sesame_Oil_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Oil_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sesame_Seeds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Seeds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Sunflower_Seeds_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sunflower_Seeds_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NutsAndOilseeds_Walnuts_Image {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Walnuts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
