//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.API.Properties.Ingredients {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IngredientImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientImages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.API.Properties.Ingredients.IngredientImages", typeof(IngredientImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_All_Purpose_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_All_Purpose_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Amaranth_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Amaranth_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Arborio_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Arborio_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barley_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barley_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Barnyard_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barnyard_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Basmati_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Basmati_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bean_Sprouts_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bean_Sprouts_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bengal_Gram__Split__Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bengal_Gram__Split__Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_eyed_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_eyed_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Black_Gram_Images {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Gram_Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Bread_Images {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bread_Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Breadcrumbs_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breadcrumbs_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Brown_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Brown_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Buckwheat_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Buckwheat_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Chickpeas_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Chickpeas_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Cornmeal_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Cornmeal_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Couscous_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Couscous_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Finger_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Finger_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Gram_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Gram_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Green_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Green_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Black_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Black_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Husked_Green_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Green_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Jowar_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Jowar_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Kidney_Beans_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Kidney_Beans_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Muesli_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Muesli_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Oats_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Oats_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pearl_Millet_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pearl_Millet_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pigeon_Pea_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pigeon_Pea_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Pressed_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pressed_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Puffed_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Puffed_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Rice_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Rice_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Semolina_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Semolina_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Tapioca_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Tapioca_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Water_Chestnut_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Water_Chestnut_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Bengal_Gram_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Bengal_Gram_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Brown_Lentils_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Brown_Lentils_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CerealsAndPulses_Whole_Wheat_Flour_Image {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Wheat_Flour_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Blue_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Blue_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Brie_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Brie_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Butter_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Butter_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Buttermilk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Buttermilk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cheddar_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cheddar_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Clarified_Butter_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Clarified_Butter_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Condensed_Milk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Condensed_Milk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cottage_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cottage_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Cream_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Feta_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Feta_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gouda_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gouda_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Gruyere_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gruyere_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Hung_Curd_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Hung_Curd_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Khoya_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Khoya_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mascarpone_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mascarpone_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Milk_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Milk_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Mozzarella_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mozzarella_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Parmesan_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Parmesan_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Provolone_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Provolone_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Ricotta_Cheese_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Ricotta_Cheese_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DairyProducts_Yogurt_Image {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Yogurt_Image", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
