//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Names.Measurements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Names_Measurements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names_Measurements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Names.Measurements.Names_Measurements", typeof(Names_Measurements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcs.
        /// </summary>
        public static string Amount_Amount {
            get {
                return ResourceManager.GetString("Amount_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table spoon.
        /// </summary>
        public static string Spoon_TableSpoon {
            get {
                return ResourceManager.GetString("Spoon_TableSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea spoon.
        /// </summary>
        public static string Spoon_TeaSpoon {
            get {
                return ResourceManager.GetString("Spoon_TeaSpoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        public static string Volume_Liter {
            get {
                return ResourceManager.GetString("Volume_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliter.
        /// </summary>
        public static string Volume_Milliliter {
            get {
                return ResourceManager.GetString("Volume_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        public static string Weight_Gram {
            get {
                return ResourceManager.GetString("Weight_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string Weight_Kilogram {
            get {
                return ResourceManager.GetString("Weight_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligram.
        /// </summary>
        public static string Weight_Milligram {
            get {
                return ResourceManager.GetString("Weight_Milligram", resourceCulture);
            }
        }
    }
}
