//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Descriptions.Recipes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Descriptions_Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions_Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Descriptions.Recipes.Descriptions_Courses", typeof(Descriptions_Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An amuse-bouche is a single, bite-sized hors d&apos;œuvre. Amuse-bouches are different from appetizers in that they are not ordered from a menu by patrons but are served free and according to the chef&apos;s selection alone. These are served both to prepare the guest for the meal and to offer a glimpse of the chef&apos;s style.
        ///
        ///The term is French and literally means &quot;mouth amuser&quot;. The plural form may be amuse-bouche or amuse-bouches. In France, amuse-gueule is traditionally used in conversation and literary writing, w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AmuseBouche {
            get {
                return ResourceManager.GetString("AmuseBouche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appetizer is a small dish of an overall meal. It can also be a drink or multiple drinks containing alcohol. Common examples include: shrimp cocktail, calamari, salad, potato skins, mussels, bruschetta or cheese and crackers. An appetizer may also be very elegant in some restaurants..
        /// </summary>
        public static string Appetizer {
            get {
                return ResourceManager.GetString("Appetizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A charcuterie board is an appetizer typically served on a wooden board or stone slab, either eaten straight from the board itself or portioned onto flatware. It features a selection of preserved foods, especially cured meats or pâtés, as well as cheeses and crackers or bread..
        /// </summary>
        public static string CheesePlate {
            get {
                return ResourceManager.GetString("CheesePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dessert is a course that concludes a meal. The course consists of sweet foods, such as candy, and possibly a beverage such as dessert wine and liqueur. Some cultures sweeten foods that are more commonly savory to create desserts. In some parts of the world there is no tradition of a dessert course to conclude a meal.
        ///
        ///The term dessert can apply to many sweets, such as biscuits, cakes, cookies, custards, gelatins, ice creams, pastries, pies, puddings, macaroons, sweet soups, tarts, and fruit salad (fruit i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entrée, in modern French table service and that of much of the English-speaking world, is a dish served before the main course of a meal. Outside North America, it is generally synonymous with the terms hors d&apos;oeuvre, appetizer, or starter..
        /// </summary>
        public static string FirstMainDish {
            get {
                return ResourceManager.GetString("FirstMainDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An hors d&apos;oeuvre, appetiser or starter is a small dish served before a meal in European cuisine. Some hors d&apos;oeuvres are served cold, others hot. Hors d&apos;oeuvres may be served at the dinner table as a part of the meal, or they may be served before seating, such as at a reception or cocktail party. Formerly, hors d&apos;oeuvres were also served between courses. There are two types of hors d&apos;oeuvre from service point of view:
        ///
        ///1. General hors d&apos;oeuvre;
        ///2. Classical hors d&apos;oeuvre.
        ///
        ///General hors d&apos;oeuvres includ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Horsdoeuvres {
            get {
                return ResourceManager.GetString("Horsdoeuvres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A palate cleanser is a serving of food or drink that removes food residue from the tongue allowing one to more accurately assess a new flavor.
        ///
        ///Palate cleansers are often used between tasting wine or cheese or other strong flavors. Pickled ginger is used as a palate cleanser between sushi pieces.
        ///
        ///Traditional French palate cleansers include sorbet, bread, apple slices, parsley and mint.
        ///
        ///Bamia is a traditional Anatolian stew that is sometimes served as a palate cleanser between food courses at ceremon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PalateCleanserCourse {
            get {
                return ResourceManager.GetString("PalateCleanserCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digestif (pronounced dee-jes-teef) is another name for an after dinner drink, or an alcoholic beverage served after dinner to help improve digestion. These drinks are served in small amounts, usually in a cordial glass, and are intended to be sipped..
        /// </summary>
        public static string PostMealDrinksAndPastries {
            get {
                return ResourceManager.GetString("PostMealDrinksAndPastries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A salad is a dish consisting of mixed ingredients, frequently vegetables. They are typically served chilled or at room temperature, though some can be served warm. Condiments and salad dressings, which exist in a variety of flavors, are often used to enhance a salad..
        /// </summary>
        public static string Salad {
            get {
                return ResourceManager.GetString("Salad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two-course meal serves either a soup/salad followed by an entrée or a main course and finishes with a dessert item..
        /// </summary>
        public static string SecondMainDish {
            get {
                return ResourceManager.GetString("SecondMainDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, milk, or water. Hot soups are additionally characterized by boiling solid ingredients in liquids in a pot until the flavors are extracted, forming a broth. Soups are similar to stews, and in some cases there may not be a clear distinction between the two; however, soups generally have more liquid (broth) than stews..
        /// </summary>
        public static string Soup {
            get {
                return ResourceManager.GetString("Soup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A course yet to be defined..
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
