//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.API.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amaranth.
        /// </summary>
        internal static string Cereal_Name_Amaranth {
            get {
                return ResourceManager.GetString("Cereal_Name_Amaranth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arborio Rice.
        /// </summary>
        internal static string Cereal_Name_Arborio_Rice {
            get {
                return ResourceManager.GetString("Cereal_Name_Arborio_Rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barnyard Millet.
        /// </summary>
        internal static string Cereal_Name_Barnyard_Millet {
            get {
                return ResourceManager.GetString("Cereal_Name_Barnyard_Millet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brown Rice.
        /// </summary>
        internal static string Cereal_Name_Brown_Rice {
            get {
                return ResourceManager.GetString("Cereal_Name_Brown_Rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finger Millet.
        /// </summary>
        internal static string Cereal_Name_Finger_Millet {
            get {
                return ResourceManager.GetString("Cereal_Name_Finger_Millet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jowar.
        /// </summary>
        internal static string Cereal_Name_Jowar {
            get {
                return ResourceManager.GetString("Cereal_Name_Jowar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kidney Beans.
        /// </summary>
        internal static string Cereal_Name_Kidney_Beans {
            get {
                return ResourceManager.GetString("Cereal_Name_Kidney_Beans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muesli.
        /// </summary>
        internal static string Cereal_Name_Muesli {
            get {
                return ResourceManager.GetString("Cereal_Name_Muesli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oats.
        /// </summary>
        internal static string Cereal_Name_Oats {
            get {
                return ResourceManager.GetString("Cereal_Name_Oats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Puffed Rice.
        /// </summary>
        internal static string Cereal_Name_Puffed_Rice {
            get {
                return ResourceManager.GetString("Cereal_Name_Puffed_Rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tapioca.
        /// </summary>
        internal static string Cereal_Name_Tapioca {
            get {
                return ResourceManager.GetString("Cereal_Name_Tapioca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Whole Bengal Gram.
        /// </summary>
        internal static string Cereal_Name_Whole_Bengal_Gram {
            get {
                return ResourceManager.GetString("Cereal_Name_Whole_Bengal_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buckwheat.
        /// </summary>
        internal static string Pulse_Name_Buckwheat {
            get {
                return ResourceManager.GetString("Pulse_Name_Buckwheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flour.
        /// </summary>
        internal static string Pulse_Name_Flour {
            get {
                return ResourceManager.GetString("Pulse_Name_Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Semolina.
        /// </summary>
        internal static string Pulse_Name_Semolina {
            get {
                return ResourceManager.GetString("Pulse_Name_Semolina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water Chestnut flour.
        /// </summary>
        internal static string Pulse_Name_Water_Chestnut_Flour {
            get {
                return ResourceManager.GetString("Pulse_Name_Water_Chestnut_Flour", resourceCulture);
            }
        }
    }
}
