//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_OtherIngredients {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_OtherIngredients() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_OtherIngredients", typeof(Images_OtherIngredients).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Agar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Agar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Ajinomoto {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Ajinomoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Almond_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Almond_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Alum {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Alum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Arrowroot {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Arrowroot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Baking_Powder {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Baking_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Baking_Soda {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Baking_Soda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Balsamic_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Balsamic_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Barfi {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Barfi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Beer {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Beer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Brown_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Brown_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Chocolate {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Chocolate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Chocolate_Chips {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Chocolate_Chips", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Cocoa {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cocoa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Coconut_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Coconut_Oil {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Coconut_Water {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coconut_Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Coffee {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Coffee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Cognac {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cognac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Cornflour {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cornflour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Cranberry_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Cranberry_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Desiccated_Coconut {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Desiccated_Coconut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Egg {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Egg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Fish_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Fish_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Flat_Noodles {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Flat_Noodles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Gelatin {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Gelatin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Glycerine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Glycerine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Gold_Leaves {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Gold_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Guchchi {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Guchchi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Hoisin_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Hoisin_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Jelly {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Jelly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Jus {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Jus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Lotus_Seeds {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Lotus_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Malt_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Malt_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Margarine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Margarine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Marzipan {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Marzipan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Mayonnaise {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Mayonnaise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Melon_Seeds {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Melon_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Meringue {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Meringue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Oyster_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Oyster_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Paan {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Paan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Papad {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Papad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Pasta {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Pasta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Petha {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Petha", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Polenta {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Polenta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Quinoa {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Quinoa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Red_Wine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Red_Wine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Red_Wine_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Red_Wine_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Rice_Flour {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Rice_Noodles {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Noodles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Rice_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rice_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Rose_Water {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rose_Water", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Roux {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Roux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Rum {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Rum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Sake {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Screw_Pine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Screw_Pine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Sea_Salt {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sea_Salt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Sev {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sev", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Sharbat {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Sharbat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Soy_Milk {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Soy_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Soya_Sauce {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Soya_Sauce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Tartaric_Acid {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tartaric_Acid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Tea {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Tofu {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tofu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Tomato_Puree {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tomato_Puree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Tortilla {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Tortilla", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vanilla_Essence {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vanilla_Essence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vegetable_Oil {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vegetable_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vermicelli {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vermicelli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vetiver {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vetiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vinaigrette {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vinaigrette", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Vinegar {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Vinegar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_White_Pepper {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_White_Pepper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_White_Wine {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_White_Wine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] OtherIngredients_Yeast {
            get {
                object obj = ResourceManager.GetObject("OtherIngredients_Yeast", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
