//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_NutsAndOilseeds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_NutsAndOilseeds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_NutsAndOilseeds", typeof(Images_NutsAndOilseeds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Almonds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Almonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Blanched_Almonds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Blanched_Almonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Canola_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Canola_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Cashew_Nuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Cashew_Nuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Chia_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chia_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Chironji {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Chironji", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Hazelnut {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Hazelnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Mustard_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Mustard_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Mustard_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Olive_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Olive_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Peanuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Peanuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Pine_Nuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pine_Nuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Pistachio {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Pistachio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Poppy_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Poppy_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Sesame_Oil {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Oil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Sesame_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sesame_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Sunflower_Seeds {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Sunflower_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NutsAndOilseeds_Walnuts {
            get {
                object obj = ResourceManager.GetObject("NutsAndOilseeds_Walnuts", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
