//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images__Fruits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images__Fruits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_ Fruits", typeof(Images__Fruits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Apples {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Apricots {
            get {
                object obj = ResourceManager.GetObject("Fruits_Apricots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Banana {
            get {
                object obj = ResourceManager.GetObject("Fruits_Banana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Blueberries {
            get {
                object obj = ResourceManager.GetObject("Fruits_Blueberries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Cape_Gooseberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cape_Gooseberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Cherry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cherry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Coconut {
            get {
                object obj = ResourceManager.GetObject("Fruits_Coconut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Cooking_Apples {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cooking_Apples", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Cranberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Cranberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Currant {
            get {
                object obj = ResourceManager.GetObject("Fruits_Currant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Custard_Apple {
            get {
                object obj = ResourceManager.GetObject("Fruits_Custard_Apple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Dates {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Dried_Fruit {
            get {
                object obj = ResourceManager.GetObject("Fruits_Dried_Fruit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Figs {
            get {
                object obj = ResourceManager.GetObject("Fruits_Figs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Grapefruit {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapefruit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Grapes {
            get {
                object obj = ResourceManager.GetObject("Fruits_Grapes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Guava {
            get {
                object obj = ResourceManager.GetObject("Fruits_Guava", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Indian_Gooseberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Indian_Gooseberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Jamun {
            get {
                object obj = ResourceManager.GetObject("Fruits_Jamun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Kiwi {
            get {
                object obj = ResourceManager.GetObject("Fruits_Kiwi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Lemon {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Lemon_Juice {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Juice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Lemon_Rind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lemon_Rind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Lychee {
            get {
                object obj = ResourceManager.GetObject("Fruits_Lychee", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Mango {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mango", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Mulberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Mulberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Olives {
            get {
                object obj = ResourceManager.GetObject("Fruits_Olives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Orange {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Orange_Rind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Orange_Rind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Papaya {
            get {
                object obj = ResourceManager.GetObject("Fruits_Papaya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Peach {
            get {
                object obj = ResourceManager.GetObject("Fruits_Peach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Pear {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Pineapple {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pineapple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Plum {
            get {
                object obj = ResourceManager.GetObject("Fruits_Plum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Pomegranate {
            get {
                object obj = ResourceManager.GetObject("Fruits_Pomegranate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Raisins {
            get {
                object obj = ResourceManager.GetObject("Fruits_Raisins", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Strawberry {
            get {
                object obj = ResourceManager.GetObject("Fruits_Strawberry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Sultana {
            get {
                object obj = ResourceManager.GetObject("Fruits_Sultana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Tamarind {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tamarind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Tomato {
            get {
                object obj = ResourceManager.GetObject("Fruits_Tomato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Water_Chestnut {
            get {
                object obj = ResourceManager.GetObject("Fruits_Water_Chestnut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits_Watermelon {
            get {
                object obj = ResourceManager.GetObject("Fruits_Watermelon", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
