//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_SpicesAndHerbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_SpicesAndHerbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_SpicesAndHerbs", typeof(Images_SpicesAndHerbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Acacia {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Acacia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Allspice {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Allspice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Aniseed {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Aniseed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Asafoetida {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Asafoetida", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Basil {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Basil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Bay_Leaf {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Bay_Leaf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Black_Cardamom {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Black_Cardamom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Black_Cumin {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Black_Cumin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Black_Pepper {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Black_Pepper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Cajun_Spices {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Cajun_Spices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Caraway_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Caraway_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Carom_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Carom_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Cayenne {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Cayenne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Chives {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Chives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Cinnamon {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Cinnamon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Cloves {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Cloves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Coriander_Leaves {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Coriander_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Coriander_Powder {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Coriander_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Coriander_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Coriander_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Cumin_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Cumin_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Curry_Leaves {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Curry_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Dill {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Dill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Dried_Fenugreek_Leaves {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Dried_Fenugreek_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Dry_Ginger_Powder {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Dry_Ginger_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Fennel {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Fennel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Fenugreek_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Fenugreek_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Five_Spice_Powder {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Five_Spice_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Galangal {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Galangal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Garam_Masala {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Garam_Masala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Green_Cardamom {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Green_Cardamom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Herbs {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Herbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Kashmiri_Mirch {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Kashmiri_Mirch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Lemongrass {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Lemongrass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Mace {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Mace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Marjoram {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Marjoram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Mint_Leaves {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Mint_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Mustard_Powder {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Mustard_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Nasturtium {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Nasturtium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Nutmeg {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Nutmeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Onion_Seeds {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Onion_Seeds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Oregano {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Oregano", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Paprika {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Paprika", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Parsley {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Parsley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Raw_Mango_Powder {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Raw_Mango_Powder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Red_Chilli {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Red_Chilli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Rock_Salt {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Rock_Salt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Rosemary {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Rosemary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Saffron {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Saffron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Sage {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Sage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Salt {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Salt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Star_Anise {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Star_Anise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Thyme {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Thyme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Tulsi {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Tulsi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Turmeric {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Turmeric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SpicesAndHerbs_Yellow_Chillies {
            get {
                object obj = ResourceManager.GetObject("SpicesAndHerbs_Yellow_Chillies", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
