//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_Vegetables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_Vegetables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_Vegetables", typeof(Images_Vegetables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Artichoke {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Artichoke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Ash_Gourd {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Ash_Gourd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Asparagus {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Asparagus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Avocado {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Avocado", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Baby_Corn {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Baby_Corn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Bamboo_Shoot {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Bamboo_Shoot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Beetroot {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Beetroot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Bell_Pepper {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Bell_Pepper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Bitter_Gourd {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Bitter_Gourd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Bok_Choy {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Bok_Choy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Bottle_Gourd {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Bottle_Gourd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Broad_Beans {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Broad_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Broccoli {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Broccoli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Cabbage {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Cabbage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Capers {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Capers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Capsicum {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Capsicum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Carrot {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Carrot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Cauliflower {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Cauliflower", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Celery {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Celery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Cherry_Tomatoes {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Cherry_Tomatoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Cluster_Beans {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Cluster_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Colocasia {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Colocasia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Corn {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Corn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Cucumber {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Cucumber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Drumstick {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Drumstick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Eggplant {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Eggplant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Fenugreek {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Fenugreek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_French_Beans {
            get {
                object obj = ResourceManager.GetObject("Vegetables_French_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Garlic {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Garlic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Gherkins {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Gherkins", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Ginger {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Ginger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Green_Chillies {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Green_Chillies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Green_Peas {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Green_Peas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Horseradish {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Horseradish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Jackfruit {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Jackfruit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Jalapeno {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Jalapeno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Kaffir_Lime {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Kaffir_Lime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Lady_Finger {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Lady_Finger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Leek {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Leek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Lettuce {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Lettuce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Lotus_Stem {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Lotus_Stem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Mushroom {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Mushroom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Mustard_Leaves {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Mustard_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Onion {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Onion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Pigweed {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Pigweed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Pimiento {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Pimiento", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Plantain {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Plantain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Potatoes {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Potatoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Pumpkin {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Pumpkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Radish {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Radish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Ridge_Gourd {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Ridge_Gourd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Rocket_Leaves {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Rocket_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Round_Gourd {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Round_Gourd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Shallots {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Shallots", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Shiitake_Mushroom {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Shiitake_Mushroom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Snake_Beans {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Snake_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Sorrel_Leaves {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Sorrel_Leaves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Spinach {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Spinach", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Spring_Onion {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Spring_Onion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Sweet_Potatoes {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Sweet_Potatoes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Turnip {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Turnip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Yam {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Yam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Vegetables_Zucchini {
            get {
                object obj = ResourceManager.GetObject("Vegetables_Zucchini", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
