//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_CerealsAndPulses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_CerealsAndPulses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_CerealsAndPulses", typeof(Images_CerealsAndPulses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_All_Purpose_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_All_Purpose_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Amaranth {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Amaranth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Arborio_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Arborio_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Barley {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Barnyard_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Barnyard_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Basmati_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Basmati_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Bean_Sprouts {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bean_Sprouts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Bengal_Gram__Split_ {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Bengal_Gram__Split_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Black_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Black_eyed_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_eyed_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Black_Grams {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Black_Grams", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Breadcrumbs {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breadcrumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Breads {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Breads", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Brown_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Brown_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Buckwheat {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Buckwheat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Chickpeas {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Chickpeas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Cornmeal {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Cornmeal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Couscous {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Couscous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Finger_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Finger_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Gram_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Gram_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Green_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Green_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Husked_Black_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Black_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Husked_Green_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Husked_Green_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Jowar {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Jowar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Kidney_Beans {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Kidney_Beans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Muesli {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Muesli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Oats {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Oats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Pearl_Millet {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pearl_Millet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Pigeon_Pea {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pigeon_Pea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Pressed_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Pressed_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Puffed_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Puffed_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Rice {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Rice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Semolina {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Semolina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Tapioca {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Tapioca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Water_Chestnut_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Water_Chestnut_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Whole_Bengal_Gram {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Bengal_Gram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Whole_Brown_Lentils {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Brown_Lentils", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CerealsAndPulses_Whole_Wheat_Flour {
            get {
                object obj = ResourceManager.GetObject("CerealsAndPulses_Whole_Wheat_Flour", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
