//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Images.Ingredients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_DairyProducts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_DairyProducts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Images.Ingredients.Images_DairyProducts", typeof(Images_DairyProducts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Blue_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Blue_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Brie_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Brie_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Butter {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Butter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Buttermilk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Buttermilk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Cheddar_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cheddar_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Clarified_Butter {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Clarified_Butter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Condensed_Milk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Condensed_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Cottage_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cottage_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Cream {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Cream_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Cream_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Feta_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Feta_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Gouda_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gouda_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Gruyere_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Gruyere_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Hung_Curd {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Hung_Curd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Khoya {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Khoya", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Mascarpone_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mascarpone_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Milk {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Milk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Mozzarella_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Mozzarella_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Parmesan_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Parmesan_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Provolone_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Provolone_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Ricotta_Cheese {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Ricotta_Cheese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DairyProducts_Yogurt {
            get {
                object obj = ResourceManager.GetObject("DairyProducts_Yogurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
