//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeGenerator.Resources.Names.Recipes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Names_Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names_Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeGenerator.Resources.Names.Recipes.Names_Courses", typeof(Names_Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amuse Bouche.
        /// </summary>
        public static string AmuseBouche {
            get {
                return ResourceManager.GetString("AmuseBouche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appetizer.
        /// </summary>
        public static string Appetizer {
            get {
                return ResourceManager.GetString("Appetizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheese Plate.
        /// </summary>
        public static string CheesePlate {
            get {
                return ResourceManager.GetString("CheesePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dessert.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Main Dish.
        /// </summary>
        public static string FirstMainDish {
            get {
                return ResourceManager.GetString("FirstMainDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horsdoeuvres.
        /// </summary>
        public static string Horsdoeuvres {
            get {
                return ResourceManager.GetString("Horsdoeuvres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palate Cleanser Course.
        /// </summary>
        public static string PalateCleanserCourse {
            get {
                return ResourceManager.GetString("PalateCleanserCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Meal Drinks And Pastries.
        /// </summary>
        public static string PostMealDrinksAndPastries {
            get {
                return ResourceManager.GetString("PostMealDrinksAndPastries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salad.
        /// </summary>
        public static string Salad {
            get {
                return ResourceManager.GetString("Salad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Main Dish.
        /// </summary>
        public static string SecondMainDish {
            get {
                return ResourceManager.GetString("SecondMainDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soup.
        /// </summary>
        public static string Soup {
            get {
                return ResourceManager.GetString("Soup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
